### ISSUE TITLE
managing chromatography equipment

### ISSUE THREAD

**Issue by maha5053** [DavidLutton/LabToolkit#16]
Hi, David! my apologies for bothering you through the issue, but we are interested in your experience in agilent equipement. We are planning to start a new project, software for managing chromatographs, and your competence might be very helpful. Do you mind to share some of your contacts, email, linkedin or smth else, where i can reach you out?

**Comment by DavidLutton** [comment]
Sorry, somehow I missed this.
Except for knowing that Agilent makes makes chemical process machines, I am only particularly familiar with the RF and electrical test equipment that Agilent manufactured between [2000 and 2013](https://www.keysight.com/us/en/about/keysight-technologies-history.html)
