### ISSUE TITLE
Error while running "python setup.py install"

### ISSUE THREAD

**Issue by adityabharadwaj14** [DavidLutton/LabToolkit#5]
* Engineering Project version:
* Python version:
* Operating System:

### Description
I was using this module to interface with HP3478A over GPIB-USB-HS cable.

While running "sudo python setup.py install" the following error showed up.
![Screenshot from 2019-12-19 16-54-49](https://user-images.githubusercontent.com/26710961/71188055-8de56200-2280-11ea-8dc1-ce06f1c79f90.png)

when i tried to import LabToolkit , it gave these same errors. Have i done something wrong in the installation or can this be solved.

```

**Comment by DavidLutton** [comment]
Nothing wrong, it is just that, I have written this library to be Python >3.6 compatible

[PEP 3102 -- Keyword-Only Arguments](https://www.python.org/dev/peps/pep-3102/) were first supported by Python 3.0

A further issue is that I have not written a driver for this HP 3478A the class in [LabToolkit
/DigitalMultimeter](https://github.com/DavidLutton/LabToolkit/blob/99b6e39a333801dc1cfc73665dde24459d244ae4/labtoolkit/DigitalMultimeter.py#L45) is a place holder at present

For programming commands you are after [03478-90009.pdf](http://literature.cdn.keysight.com/litweb/pdf/03478-90009.pdf) 
Page 43 to 70 where you can skip the status byte, SRQ and SPOLL until you have need of it
The examples are in the document are in BASIC  

Where in BASIC:
`10 OUTPUT 723; "F1R1"`  
`20 ENTER 723; A$`  
`30 DISP $A`  
In Python 3
`import visa`  
`rm = visa.ResourceManager('')`  
`inst = rm.open_resource('GPIB0::23::INSTR', read_termination='\n', write_termination='\n')`  
`inst.write('F1R1')`  
`a = inst.read()`  
`print(a)`  

or 
`import visa`  
`rm = visa.ResourceManager('')`  
`inst = rm.open_resource('GPIB0::23::INSTR', read_termination='\n', write_termination='\n')`  
`a = inst.query('F1R1')`  
`print(a)`  

In Python 2, if you must use it with its [limited support life](https://pythonclock.org/), you drop the brackets on the print statements

Good luck
